modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/lemon-slice-studio/After-the-Drizzle/issues"
[[mods]] #mandatory
modId="afterthedrizzle" #mandatory
version="${file.jarVersion}" #mandatory
displayName="After the Drizzle" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/after-the-drizzle"
logoFile="atd.png" #optional
credits="Lemon Slice Studio, MalayP, jiahuayu" #optional
authors="RoitoLeonine, Gloridifice" #optional
description=''' '''
[[dependencies.afterthedrizzle]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.afterthedrizzle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.afterthedrizzle]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.4,)"
    ordering="NONE"
    side="BOTH"
